spring:
  datasource:
    url: jdbc:postgresql://loventure-prod-auth-service-postgres:5432/auth
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
